name: CD

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Deploy AWS CDK Typescript Stack
    runs-on: ubuntu-latest
    steps:
      - name: Initiated by user
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: update npm
        run: npm i -g npm@latest

      - name: Install Dependencies
        run: npm ci

      - name: Build CDK Stack
        run: npm run build

      - name: Deploy AWS CDK Stack
        run: "npx cdk deploy MyFirstCdkStack --ci --require-approval never --no-asset-metadata"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
